### ISSUE TITLE
Question about setup for telescope w/ fzf-native

### ISSUE THREAD

**Issue by tjdevries** [jake-stewart/telescope-jfind-fzf-benchmark#1]
Hey! First off, sorry for a bunch of people being jerks on reddit. I think it's cool to see other fuzzy finders in Neovim :)

I was just wondering what the config you used for telescope w/ fzf-native was. It doesn't make much sense to me that it showed up slower than the original telescope configuration. Would you mind pasting in the config you used? If anything, it's something I'd want to investigate on my side to see if something is going wrong.

Anyway, this benchmark stuff is really cool! 

Thanks

**Comment by jake-stewart** [comment]
hi, I used the default configuration as shown on the [telescope-fzf-native](https://github.com/nvim-telescope/telescope-fzf-native.nvim) readme.

you can see in this video that it appears to work, since i get the fzf searching features. i also checked the build directory for telescope-fzf-native and it was all built. https://streamable.com/yu6z54

```
    {
        'nvim-telescope/telescope.nvim',
        tag = '0.1.1',
        dependencies = { 'nvim-lua/plenary.nvim' }
    },

    {
        'nvim-telescope/telescope-fzf-native.nvim',
        build = 'cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build',
        config = function()
            require('telescope').setup {
                extensions = {
                    fzf = {
                        fuzzy = true,
                        override_generic_sorter = true,
                        override_file_sorter = true,
                        case_mode = "smart_case",
                    }
                }
            }
            require('telescope').load_extension('fzf')
        end
    },

```
